### ISSUE TITLE
Allow printing to a non-terminal if desired

### ISSUE THREAD

**Issue by jojomi** [gernest/wow#10]
I plan to use your library in github.com/jojomi/go-script where it looks like a natural fit.

For the test cases I would like to verify we get somewhat expected output. I am aware it will not be fully testable, but I would at least verify we get any output to prevent bad regressions. In a testcase it would be nice if I could set `isTerminal` to true no matter if it is a terminal to check if I see the output requested. Would you consider adding something like `func (w *Wow) SetOutputOutsideTerminal(value bool)`?

**Comment by gernest** [comment]
see #13
